# Generated by Django 2.1.7 on 2019-05-27 05:28

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_uploadfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=upload.models.upload_unique_loc),
        ),
    ]
