# Generated by Django 2.1.7 on 2019-05-27 05:37

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190527_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=upload.models.upload_location),
        ),
    ]
